# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/accountdialog.ui'
#
# Created: Sun Aug  7 01:16:49 2011
#      by: pyside-uic 0.2.9 running on PySide 1.0.5
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_AccountDialog(object):
    def setupUi(self, AccountDialog):
        AccountDialog.setObjectName("AccountDialog")
        AccountDialog.resize(300, 300)
        AccountDialog.setMinimumSize(QtCore.QSize(300, 300))
        AccountDialog.setMaximumSize(QtCore.QSize(300, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/blusage.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AccountDialog.setWindowIcon(icon)
        self.gridLayout = QtGui.QGridLayout(AccountDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtGui.QLabel(AccountDialog)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.accountNameEdit = QtGui.QLineEdit(AccountDialog)
        self.accountNameEdit.setObjectName("accountNameEdit")
        self.horizontalLayout_4.addWidget(self.accountNameEdit)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.line_3 = QtGui.QFrame(AccountDialog)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 1, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(AccountDialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.usernameEdit = QtGui.QLineEdit(AccountDialog)
        self.usernameEdit.setObjectName("usernameEdit")
        self.horizontalLayout.addWidget(self.usernameEdit)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(AccountDialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.passwordEdit = QtGui.QLineEdit(AccountDialog)
        self.passwordEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.passwordEdit.setObjectName("passwordEdit")
        self.horizontalLayout_2.addWidget(self.passwordEdit)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(17, 8, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.line_4 = QtGui.QFrame(AccountDialog)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 5, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtGui.QLabel(AccountDialog)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.fromDate = QtGui.QDateEdit(AccountDialog)
        self.fromDate.setCalendarPopup(True)
        self.fromDate.setObjectName("fromDate")
        self.verticalLayout.addWidget(self.fromDate)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtGui.QLabel(AccountDialog)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.toDate = QtGui.QDateEdit(AccountDialog)
        self.toDate.setCalendarPopup(True)
        self.toDate.setObjectName("toDate")
        self.verticalLayout_2.addWidget(self.toDate)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 6, 0, 1, 1)
        self.line_2 = QtGui.QFrame(AccountDialog)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 7, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtGui.QLabel(AccountDialog)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.capEdit = QtGui.QLineEdit(AccountDialog)
        self.capEdit.setEchoMode(QtGui.QLineEdit.Normal)
        self.capEdit.setObjectName("capEdit")
        self.horizontalLayout_6.addWidget(self.capEdit)
        self.gridLayout.addLayout(self.horizontalLayout_6, 8, 0, 1, 1)
        self.line = QtGui.QFrame(AccountDialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 9, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtGui.QSpacerItem(37, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.cancelButton = QtGui.QPushButton(AccountDialog)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_5.addWidget(self.cancelButton)
        self.saveButton = QtGui.QPushButton(AccountDialog)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_5.addWidget(self.saveButton)
        self.gridLayout.addLayout(self.horizontalLayout_5, 10, 0, 1, 1)

        self.retranslateUi(AccountDialog)
        QtCore.QObject.connect(self.cancelButton, QtCore.SIGNAL("clicked()"), AccountDialog.reject)
        QtCore.QObject.connect(self.saveButton, QtCore.SIGNAL("clicked()"), AccountDialog.accept)
        QtCore.QMetaObject.connectSlotsByName(AccountDialog)

    def retranslateUi(self, AccountDialog):
        AccountDialog.setWindowTitle(QtGui.QApplication.translate("AccountDialog", "Account credentials", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("AccountDialog", "Account Name", None, QtGui.QApplication.UnicodeUTF8))
        self.accountNameEdit.setPlaceholderText(QtGui.QApplication.translate("AccountDialog", "Name your account", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("AccountDialog", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.usernameEdit.setPlaceholderText(QtGui.QApplication.translate("AccountDialog", "Your BanglaLion username", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("AccountDialog", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.passwordEdit.setPlaceholderText(QtGui.QApplication.translate("AccountDialog", "Your BanglaLion password", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("AccountDialog", "From", None, QtGui.QApplication.UnicodeUTF8))
        self.fromDate.setDisplayFormat(QtGui.QApplication.translate("AccountDialog", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("AccountDialog", "To", None, QtGui.QApplication.UnicodeUTF8))
        self.toDate.setDisplayFormat(QtGui.QApplication.translate("AccountDialog", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("AccountDialog", "Your Cap. (in KB)", None, QtGui.QApplication.UnicodeUTF8))
        self.capEdit.setPlaceholderText(QtGui.QApplication.translate("AccountDialog", "Enter your limit here", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("AccountDialog", "&Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("AccountDialog", "&Save", None, QtGui.QApplication.UnicodeUTF8))

import blusage_rc
